In [1]:
# Import libraries
import numpy as np
from scipy.ndimage import convolve

## Explanation

Below is the code for the initial set up proposed in the document we were given on Monday. 
We should look to define the code below in two seperate functions for clarity that can then be used to judge changes over time

In terms of improving our model here are some initial thoughts:
1) Larger range of house values with their probabilities of occurence and the values themselves decided by referenced research for a specific city/town
2) Consider the most important neighbourhood properties and either incorporate them into our equations or define new equations
3) change size of neighbourhood but also weighting of neighbourhood (the immediate neighbours should have a more significant impact than neighbours further away)
4) Perhaps we could add some changes in income over time to match the development of salaries?
5) Find a way to model the fact that people leave and enter new cities all the time. Have a proportion of people leave the city and enter the city at each timestep.

In [2]:
# Create matrices to keep track of house prices and corresponding house owners

# Define lattice size
n = 10
m = 10

# Create lattice of house prices
house_values = [100, 500, 1000] # Adjust accordingly
house_probabilities = [0.5, 0.3, 0.2] # Adjust accordingly
V = np.random.choice(house_values, size = (n,m), p = house_probabilities)


# Create lattice of house owners
# Poor = 0.1
# Middle = 0.5
# Rich = 1
income_values = [0.1,0.5,1.0]
income_probabilities = [0.5, 0.3, 0.2]
A = np.random.choice(income_values, size = (n,m), p = income_probabilities)

print("House Prices (V):\n", V)
print("\nIncome Levels (A):\n", A)

House Prices (V):
 [[ 500  100  100  100  100  100  500  100  500  100]
 [ 100  100  500 1000  100  100  500  100  100  100]
 [ 500  100 1000  500  100  500  500  500  100  500]
 [1000  100  500  100  500 1000  100  100 1000  100]
 [ 100  500 1000  100 1000  100  100  100  100  100]
 [1000  100 1000 1000 1000  500  100 1000 1000  100]
 [ 500  500  500 1000 1000  100  500  100  100  100]
 [1000  100 1000  100  500  100  500  100  500  100]
 [ 500 1000  100  100  100  500  100 1000  100  500]
 [ 500  100 1000  100  100 1000  500  500  500 1000]]

Income Levels (A):
 [[0.5 1.  0.5 0.1 0.5 1.  0.1 0.1 0.1 0.1]
 [0.5 0.5 0.1 0.5 0.1 0.5 0.5 0.5 0.5 0.5]
 [0.1 0.1 1.  0.1 1.  0.1 0.5 0.1 1.  0.5]
 [1.  0.1 0.1 1.  0.5 0.1 0.1 0.1 0.1 0.1]
 [1.  0.1 0.1 0.1 0.5 0.5 0.5 0.1 0.1 0.1]
 [0.1 1.  0.1 0.1 0.1 0.5 0.1 0.5 1.  0.5]
 [0.5 0.5 0.1 0.5 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.5 0.1 0.1 0.1 0.5 0.5 0.1 0.1 0.1]
 [0.1 0.1 0.5 0.1 0.1 0.5 0.1 0.1 1.  0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 1.  0.1 0.5]

In [ ]:
# Update house values

old_V = V.copy()
z = 1 # coefficient value (change as necessary) # z is lambda...

# Define Neighbourhood area size
neighbourhood = np.ones((5,5))

# Computes sum of neighbourhood house values and number of neighbours using convolution
# constant mode with cval = 0 treats anything outside of edges of matrix as zero
# Search up convolve function to understand this part
neighbourhood_sum = convolve(old_V, neighbourhood, mode='constant', cval = 0)
neighbourhood_count = convolve(np.ones((n,m)), neighbourhood, mode='constant', cval = 0)

# Use equation given in worksheet to calculate new values of houses
V = np.round(A + z * (neighbourhood_sum / neighbourhood_count))

print("Sum of Neighbourhood House Values:\n", neighbourhood_sum) 
print("Number of Neighbours:\n", neighbourhood_count)
print("Updated House Prices:\n", new_V)

Sum of Neighbourhood House Values:
 [[ 3000  4600  4900  4500  5700  4800  3900  4300  3600  2100]
 [ 4600  6300  7100  6700  7900  6600  6600  6600  4900  3300]
 [ 6200  8000  9800  9400 10200  8000  8000  7100  5300  3600]
 [ 7600 10300 13000 12500 12900 10700 10300  8500  6300  5000]
 [ 8400 11100 14700 13800 13800 11600 11200  8500  6300  5000]
 [ 8900 11200 15200 13400 13400 10800 11200  7700  5900  4600]
 [ 8900 11200 14800 13000 12100 10800 10300  7600  6300  5000]
 [ 8900 11200 13900 12600 12500 11600 11500 10600  8400  6700]
 [ 6800  8100  9800  9000  8900  8000  7900  7900  6200  4600]
 [ 5300  5600  6300  5900  5800  5300  6100  7000  5400  4300]]
Number of Neighbours:
 [[ 9. 12. 15. 15. 15. 15. 15. 15. 12.  9.]
 [12. 16. 20. 20. 20. 20. 20. 20. 16. 12.]
 [15. 20. 25. 25. 25. 25. 25. 25. 20. 15.]
 [15. 20. 25. 25. 25. 25. 25. 25. 20. 15.]
 [15. 20. 25. 25. 25. 25. 25. 25. 20. 15.]
 [15. 20. 25. 25. 25. 25. 25. 25. 20. 15.]
 [15. 20. 25. 25. 25. 25. 25. 25. 20. 15.]
 [15. 20.

NameError: name 'new_V' is not defined

In [4]:
# Propose a move

# Flattened choice using numpy
total_grid_cells = n * m

# Randomly selects a number between 0 and the total number of grid cells
flat_indices = np.random.choice(total_grid_cells, size=2, replace=False)  # replace=False to ensure distinct choices
print(flat_indices)

# Translate value back into distinct gridspace 
# divmod does i1 = flat_indices // m, j1 = flat_indices % m
i1, j1 = divmod(flat_indices[0], m)
i2, j2 = divmod(flat_indices[1], m)

print("Random position 1:", (i1,j1))
print("Random position 2:", (i2,j2))

# Calculate value of Delta function given by the worksheet
d = (A[i1,j1] - V[i1,j1])**2 + (A[i2,j2] - V[i2,j2])**2 - (A[i1,j1] - V[i2,j2])**2 - (A[i2,j2] - V[i1,j1])**2 

# Swap inhabitants if delta value is positive
if d > 0:
    A[i1,j1], A[i2,j2] = A[i2,j2], A[i1,j1]

    
print("Delta Value: ", d)
print(A)


[53  1]
Random position 1: (np.int64(5), np.int64(3))
Random position 2: (np.int64(0), np.int64(1))
Delta Value:  273.5999999999767
[[0.5 0.1 0.5 0.1 0.5 1.  0.1 0.1 0.1 0.1]
 [0.5 0.5 0.1 0.5 0.1 0.5 0.5 0.5 0.5 0.5]
 [0.1 0.1 1.  0.1 1.  0.1 0.5 0.1 1.  0.5]
 [1.  0.1 0.1 1.  0.5 0.1 0.1 0.1 0.1 0.1]
 [1.  0.1 0.1 0.1 0.5 0.5 0.5 0.1 0.1 0.1]
 [0.1 1.  0.1 1.  0.1 0.5 0.1 0.5 1.  0.5]
 [0.5 0.5 0.1 0.5 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.5 0.1 0.1 0.1 0.5 0.5 0.1 0.1 0.1]
 [0.1 0.1 0.5 0.1 0.1 0.5 0.1 0.1 1.  0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 1.  0.1 0.5]]
